site_name: Horolezeck√° Kronika
site_description: Kroniky z√°≈æitk≈Ø z na≈°ich spoleƒçn√Ωch horolezeck√Ωch v√Ωprav
site_url: https://horolezecka-kronika.eu

# Nastaven√≠ grafick√©ho t√©matu
theme:
  name: material
  language: cs
  custom_dir: overrides
  palette: 
    # Svƒõtl√Ω re≈æim
    - scheme: default
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: P≈ôepnout do tmav√©ho re≈æimu
    # Tmav√Ω re≈æim
    - scheme: slate
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: P≈ôepnout do svƒõtl√©ho re≈æimu
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - search.highlight
    - search.suggest
    - content.code.copy
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/terrain

# Pluginy
plugins:
  - search:
      lang: cs
  - glightbox:     
      touchNavigation: true
      loop: true
      zoomable: true
      width: 90%
      height: 90%
  - encryptcontent:
      title_prefix: '[üîí] '
      summary: 'Tato str√°nka je chr√°nƒõna heslem.'
      placeholder: 'Zadejte heslo'
      decryption_failure_message: 'Nespr√°vn√© heslo!'
      encryption_info_message: 'Pro zobrazen√≠ obsahu zadejte heslo.'
      global_password: 'Alpy2026'
      # search_index: encrypted
      # encryption_type: 'Fernet'
      # na zaƒç√°tek jednl. st√°nek p≈ôidat:
      # ---
      # encrypt: true
      # password: 'Alpy2026'
      # ---

# Roz≈°√≠≈ôen√≠ Markdown
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables

# Struktura navigace
nav:
  - √övod: index.md
  - O n√°s: o-nas.md
  - Pl√°novan√° dovolen√° 2026: planovana-dovolena-2026.md
  - 2025 - Slovinsko: 2025-slovinsko.md
  - 2024 - It√°lie (Ledro II): 2024-italie-ledro-2.md
  - 2023 - It√°lie (Ledro I.): 2023-italie-ledro-1.md
  - 2022 - Dolomity II.: 2022-dolomity-2.md
  - 2021 - Dolomity I.: 2021-dolomity-1.md

# Extra CSS a JS
extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/solid/mountain
      name: Horolezeck√° kronika